DATA_PATH = "../data/"
HTML_PATH = "../visual/"
IN_FILE = "common_ludo.tsv"
OUT_FILE = "common_ludo.html"

headers = []
filei = open(DATA_PATH + IN_FILE, "r")
fileo = open(HTML_PATH + OUT_FILE, "w")
fileo.write("<html>\n")
fileo.write("<head>\n")
fileo.write("<meta charset=\"UTF-8\">\n")
fileo.write("<title>Common PC collection</title>\n")
fileo.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\n")
fileo.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.datatables.net/1.10.16/css/jquery.dataTables.css\">\n")
fileo.write("<script type=\"text/javascript\" charset=\"utf8\" src=\"http://cdn.datatables.net/1.10.16/js/jquery.dataTables.js\"></script>\n")
fileo.write("<style>\n")
fileo.write("\ta {\n")
fileo.write("\t\tcolor: black;\n")
fileo.write("\t\ttext-decoration: none;\n")
fileo.write("\t}\n")
fileo.write("\ta:hover {\n")
fileo.write("\t\ttext-decoration: underline;\n")
fileo.write("\t}\n")
fileo.write("</style>\n")
fileo.write("</head>\n")
fileo.write("<body bgcolor=\"white\">\n")
fileo.write("\t<table id=\"commons\" class=\"display\" width=\"100%\" cellspacing=\"0\">\n")
fileo.write("\t\t<thead>\n")
fileo.write("\t\t\t<tr>\n")
fileo.write("\t\t\t\t<th>ID</th>\n")
fileo.write("\t\t\t\t<th>Name</th>\n")
fileo.write("\t\t\t\t<th>Photo</th>\n")
fileo.write("\t\t\t\t<th>Users</th>\n")
fileo.write("\t\t\t\t<th>PC rating</th>\n")
fileo.write("\t\t\t\t<th>BGG ranking</th>\n")
fileo.write("\t\t\t\t<th>Year</th>\n")
fileo.write("\t\t\t\t<th>Players</th>\n")
fileo.write("\t\t\t\t<th>Playtime</th>\n")
fileo.write("\t\t\t\t<th>Age</th>\n")
fileo.write("\t\t\t\t<th>Categories</th>\n")
fileo.write("\t\t\t\t<th>Mechanics</th>\n")
fileo.write("\t\t\t\t<th>Base?</th>\n")
fileo.write("\t\t\t\t<th>New?</th>\n")
fileo.write("\t\t\t</tr>\n")
fileo.write("\t\t</thead>\n")
fileo.write("\t\t<tfoot>\n")
fileo.write("\t\t\t<tr>\n")
fileo.write("\t\t\t\t<th>ID</th>\n")
fileo.write("\t\t\t\t<th>Name</th>\n")
fileo.write("\t\t\t\t<th>Photo</th>\n")
fileo.write("\t\t\t\t<th>Users</th>\n")
fileo.write("\t\t\t\t<th>PC rating</th>\n")
fileo.write("\t\t\t\t<th>BGG ranking</th>\n")
fileo.write("\t\t\t\t<th>Year</th>\n")
fileo.write("\t\t\t\t<th>Players</th>\n")
fileo.write("\t\t\t\t<th>Playtime</th>\n")
fileo.write("\t\t\t\t<th>Age</th>\n")
fileo.write("\t\t\t\t<th>Categories</th>\n")
fileo.write("\t\t\t\t<th>Mechanics</th>\n")
fileo.write("\t\t\t\t<th>Base?</th>\n")
fileo.write("\t\t\t\t<th>New?</th>\n")
fileo.write("\t\t\t</tr>\n")
fileo.write("\t\t</tfoot>\n")
fileo.write("\t\t<tbody>\n")
for line in filei:
	if len(headers) == 0:
		headers = line[:-1].split("\t")
		continue
	splitline = line[:-1].split("\t")
	fileo.write("\t\t\t<tr>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("id")] + "</td>\n")
	fileo.write("\t\t\t\t<td><a target=\"_blank\" href=\"" + splitline[headers.index("link")] + "\">" + splitline[headers.index("name")] + "</a></td>\n")
	fileo.write("\t\t\t\t<td><img src=\"" + splitline[headers.index("photo")] + "\" height=\"70\"></td>\n")
	usersplit = splitline[headers.index("users")].split(",")
	fileo.write("\t\t\t\t<td>" + "<br>".join(usersplit) + "</span></td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("pc_rating")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("bgg_ranking")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("yearpublished")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("minplayers")] + "-" + splitline[headers.index("maxplayers")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("playingtime")] + " (" + splitline[headers.index("minplaytime")] + "-" + splitline[headers.index("maxplaytime")] + ")</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("minage")] + "</td>\n")
	categoriesplit = splitline[headers.index("categories")].split(",")
	mechanicsplit = splitline[headers.index("mechanics")].split(",")
	fileo.write("\t\t\t\t<td>" + "<span title=\"" + "\n".join(categoriesplit) + "\">" + "<br>".join(categoriesplit[:3]) + (" (...)" if len(categoriesplit) > 3 else "") + "</td>\n")
	fileo.write("\t\t\t\t<td>" + "<span title=\"" + "\n".join(mechanicsplit) + "\">" + "<br>".join(mechanicsplit[:3]) + (" (...)" if len(mechanicsplit) > 3 else "") + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("basegame")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("new")] + "</td>\n")
	fileo.write("\t\t\t</tr>\n")
fileo.write("\t\t</tbody>\n")
fileo.write("\t</table>\n")
fileo.write("<script>\n")
fileo.write("$(document).ready( function () {\n")
fileo.write("\t$('#commons').DataTable();\n")
fileo.write("} );\n")
fileo.write("</script>\n")
fileo.write("</body>\n")
fileo.write("</html>\n")
fileo.close()
filei.close()