DATA_PATH = "../data/"
HTML_PATH = "../visual/"
IN_FILE = "common_ludo.tsv"
OUT_FILE = "common_ludo.html"

headers = []
filei = open(DATA_PATH + IN_FILE, "r")
fileo = open(HTML_PATH + OUT_FILE, "w")
fileo.write("<html>\n")
fileo.write("<head>\n")
fileo.write("<meta charset=\"UTF-8\">\n")
fileo.write("<title>Common PC collection</title>\n")
fileo.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\n")
fileo.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.datatables.net/1.10.16/css/jquery.dataTables.css\">\n")
fileo.write("<script type=\"text/javascript\" charset=\"utf8\" src=\"http://cdn.datatables.net/1.10.16/js/jquery.dataTables.js\"></script>\n")
fileo.write("<style>\n")
fileo.write("\ta {\n")
fileo.write("\t\tcolor: black;\n")
fileo.write("\t\ttext-decoration: none;\n")
fileo.write("\t}\n")
fileo.write("\ta:hover {\n")
fileo.write("\t\ttext-decoration: underline;\n")
fileo.write("\t}\n")
fileo.write("</style>\n")
fileo.write("</head>\n")
fileo.write("<body bgcolor=\"white\">\n")
fileo.write("\t<table id=\"commons\" class=\"display\" width=\"100%\" cellspacing=\"0\">\n")
fileo.write("\t\t<thead>\n")
fileo.write("\t\t\t<tr>\n")
fileo.write("\t\t\t\t<th>ID</th>\n")
fileo.write("\t\t\t\t<th>Name</th>\n")
fileo.write("\t\t\t\t<th>Photo</th>\n")
fileo.write("\t\t\t\t<th>Users</th>\n")
fileo.write("\t\t\t\t<th>PC rating</th>\n")
fileo.write("\t\t\t\t<th>BGG ranking</th>\n")
fileo.write("\t\t\t\t<th>Year</th>\n")
fileo.write("\t\t\t\t<th>Players</th>\n")
fileo.write("\t\t\t\t<th>Playtime</th>\n")
fileo.write("\t\t\t\t<th>Age</th>\n")
fileo.write("\t\t\t\t<th>Categories</th>\n")
fileo.write("\t\t\t\t<th>Mechanics</th>\n")
fileo.write("\t\t\t\t<th>Base?</th>\n")
fileo.write("\t\t\t\t<th>New?</th>\n")
fileo.write("\t\t\t</tr>\n")
fileo.write("\t\t</thead>\n")
fileo.write("\t\t<tfoot>\n")
fileo.write("\t\t\t<tr>\n")
fileo.write("\t\t\t\t<th>ID</th>\n")
fileo.write("\t\t\t\t<th>Name</th>\n")
fileo.write("\t\t\t\t<th>Photo</th>\n")
fileo.write("\t\t\t\t<th>Users</th>\n")
fileo.write("\t\t\t\t<th>PC rating</th>\n")
fileo.write("\t\t\t\t<th>BGG ranking</th>\n")
fileo.write("\t\t\t\t<th>Year</th>\n")
fileo.write("\t\t\t\t<th>Players</th>\n")
fileo.write("\t\t\t\t<th>Playtime</th>\n")
fileo.write("\t\t\t\t<th>Age</th>\n")
fileo.write("\t\t\t\t<th>Categories</th>\n")
fileo.write("\t\t\t\t<th>Mechanics</th>\n")
fileo.write("\t\t\t\t<th>Base?</th>\n")
fileo.write("\t\t\t\t<th>New?</th>\n")
fileo.write("\t\t\t</tr>\n")
fileo.write("\t\t</tfoot>\n")
fileo.write("\t\t<tbody>\n")
for line in filei:
	if len(headers) == 0:
		headers = line[:-1].split("\t")
		continue
	splitline = line[:-1].split("\t")
	fileo.write("\t\t\t<tr>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("id")] + "</td>\n")
	fileo.write("\t\t\t\t<td><a target=\"_blank\" href=\"" + splitline[headers.index("link")] + "\"><b>" + splitline[headers.index("name")] + "</b></a></td>\n")
	fileo.write("\t\t\t\t<td><img src=\"" + splitline[headers.index("photo")] + "\" height=\"70\"></td>\n")
	usersplit = splitline[headers.index("users")].split(",")
	fileo.write("\t\t\t\t<td>" + "<br>".join(usersplit) + "</span></td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("pc_rating")] + "</td>\n")
	fileo.write("\t\t\t\t<td data-order=\"" + (splitline[headers.index("bgg_ranking")] if splitline[headers.index("bgg_ranking")] != "" else "7777777") + "\">" + splitline[headers.index("bgg_ranking")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("yearpublished")] + "</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("minplayers")] + "-" + splitline[headers.index("maxplayers")] + "</td>\n")
	fileo.write("\t\t\t\t<td data-order=\"" + (splitline[headers.index("playingtime")] if splitline[headers.index("playingtime")]!= "" else "0") + "\">" + splitline[headers.index("playingtime")] + " (" + splitline[headers.index("minplaytime")] + "-" + splitline[headers.index("maxplaytime")] + ")</td>\n")
	fileo.write("\t\t\t\t<td>" + splitline[headers.index("minage")] + "</td>\n")
	categoriesplit = splitline[headers.index("categories")].split(",")
	mechanicsplit = splitline[headers.index("mechanics")].split(",")
	fileo.write("\t\t\t\t<td>" + "<br>".join(categoriesplit) + "</td>\n")
	fileo.write("\t\t\t\t<td>" + "<br>".join(mechanicsplit) + "</td>\n")
	fileo.write("\t\t\t\t<td>" + ("base" if splitline[headers.index("basegame")]=="1" else "expa") + "</td>\n")
	fileo.write("\t\t\t\t<td>" + ("<span style=\"color:green;\">NEW!</span>" if splitline[headers.index("new")] == "1" else "") + "</td>\n")
	fileo.write("\t\t\t</tr>\n")
fileo.write("\t\t</tbody>\n")
fileo.write("\t</table>\n")
fileo.write("<script>\n")
fileo.write("$(document).ready( function () {\n")
fileo.write("\t$('#commons').DataTable({\n")
fileo.write("\t\t\"columnDefs\": [\n")
fileo.write("\t\t\t{\n")
fileo.write("\t\t\t\t\"targets\": [ 0 ],\n")
fileo.write("\t\t\t\t\"visible\": false,\n")
fileo.write("\t\t\t\t\"searchable\": false\n")
fileo.write("\t\t\t},\n")
fileo.write("\t\t\t{\n")
fileo.write("\t\t\t\t\"targets\": [ 2 ],\n")
fileo.write("\t\t\t\t\"searchable\": false\n")
fileo.write("\t\t\t},\n")
fileo.write("\t\t\t{\n")
fileo.write("\t\t\t\t\"targets\": [ 2,3,10,11 ],\n")
fileo.write("\t\t\t\t\"orderable\": false\n")
fileo.write("\t\t\t},\n")
fileo.write("\t\t\t{\n")
fileo.write("\t\t\t\t\"targets\": [ 10,11 ],\n")
fileo.write("\t\t\t\t\"width\": \"250\"\n")
fileo.write("\t\t\t},\n")
fileo.write("\t\t\t{\n")
fileo.write("\t\t\t\t\"targets\": [ 3 ],\n")
fileo.write("\t\t\t\t\"width\": \"100\"\n")
fileo.write("\t\t\t},\n")
fileo.write("\t\t\t{\n")
fileo.write("\t\t\t\t\"targets\": [ 4,5,6 ],\n")
fileo.write("\t\t\t\t\"type\": \"num\"\n")
fileo.write("\t\t\t}\n")
fileo.write("\t\t]\n")
fileo.write("\t});\n")
fileo.write("} );\n")
fileo.write("</script>\n")
fileo.write("</body>\n")
fileo.write("</html>\n")
fileo.close()
filei.close()